version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: myedspace-tutor-manager
        working_dir: /var/www
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
        networks:
            - my-network

    web:
        image: nginx:latest
        container_name: nginx
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        networks:
            - my-network
        depends_on:
            - app
        command: [ "nginx", "-g", "daemon off;" ]
    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: "123456"
            MYSQL_DATABASE: myedspace-tutor-manager
        volumes:
            - ./db_data:/var/lib/mysql
        ports:
            - "3307:3306"
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
