<?php

namespace Tests\Unit;

use App\Services\StudentService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class StudentServiceTest extends TestCase
{
    use DatabaseTransactions;
    private StudentService $studentService;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->studentService = new StudentService();
    }

    public function test_get_total_number_of_registered_students_success()
    {
        $result=$this->studentService->getTotalNumberOfRegisteredStudents();
        $this->assertDatabaseCount('students',$result);
    }
}
