<?php

namespace Tests\Unit;

use App\Services\TutorService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class TutorServiceTest extends TestCase
{
    use DatabaseTransactions;

    private TutorService $tutorService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->tutorService = new TutorService();
    }

    public function test_get_total_active_tutors_success()
    {
        $result = $this->tutorService->getTotalActiveTutors();
        $this->assertTrue($result >= 0);
    }

    public function test_get_highest_paid_subject_success()
    {
        $result = $this->tutorService->getHighestPaidSubject();
        $this->assertTrue(!empty($result) || $result === null);
    }

    public function test_get_average_hourly_rates_success()
    {
        $result = $this->tutorService->getAverageHourlyRate();
        $this->assertTrue($result >= 0);
    }

    public function test_max_rate_tutors_success()
    {
        $result = $this->tutorService->getMaxRateTutor();
        $this->assertTrue($result >= 0);
    }
}
